### ISSUE TITLE
json SEND crashes collector when listener recycles

### ISSUE THREAD

**Issue by jepries** [CESNET/ipfixcol#177] opened 2016-08-16 14:19 UTC
HI Guys.  Again, great work on this project, I love it.

One thing I noticed.  I have my ipfixcol using json writer, it writes files and also SENDS to a logstash listener on another machine.

As I play with logstash and reconfigure the filter to process the ipfixcol json data (oh, by the way, I had to modify the code to get rid of "ipfix." on all the outgoing json elements so that elasticsearch doesn't barf), when the logstash listener recycles the connection after a config change, ipfixcol just crashes without any messages (nothing in syslog).  I'm running on RHEL7 sending to logstash on another RHEL7.

Not sure if you guys have witnessed this behavior or not.

**Comment by Lukas955** [comment] 2016-08-17 12:09
Good point. It should be fixed in the current devel branch. Because the bug was in the SISO library (part of the IPFIXcol base), you have to rebuild the IPFIXcol base and json plugin.
The crash was caused by an unhandled signal after disconnection. Now, when the destination is disconnected, the plugin will try to reconnect it once per second.

**Closed by Lukas955** 2016-08-17 12:09 UTC

**Comment by jepries** [comment] 2016-08-17 12:22
@Lukas955 Awesome!  Thanks, i'll merge the latest and get it running!  Thanks for the quick reply!
