### ISSUE TITLE
Last flow seemingly having all bits in all fields set to 1

### ISSUE THREAD

**Issue by DRiKE** [CESNET/ipfixcol#105] opened 2015-06-16 14:18 UTC
There seems to be a problem with the 'last' flow in a result set, e.g.:

    fbitdump -R path/to/fbit_flows -A%scrip6,%dstip6 -m%flDESC -c10

sometimes yields:

            Date flow start  Duration                                Dst IPv6:Packets    Bytes Flows
    584556019-04-03 15:.615         0 ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff:214.7 T  214.7 T 50000
    (...)

This also happens when not sorting DESC and not limiting the number of results.

**Comment by thorgrin** [comment] 2015-06-17 13:46
Unfortunately, I cannot reproduce the issue. Could you provide a sample data set? Thanks

**Comment by thorgrin** [comment] 2015-07-21 03:55
The issue was caused by fastbit output plugin which incorrectly stored the data. It should be fixed now in the devel branch.

**Closed by thorgrin** 2015-07-21 03:55 UTC
